### ISSUE TITLE
Transaction Error: proto.005-PsBabyM1.storage_exhausted.operation

### ISSUE THREAD

**Issue by sriney-staked** [habanoz/tezos-reward-distributor#165]
After upgrade to the new storage, get Transaction Error in the batch.
https://tzstats.com/ooFyHioC3wnDXeumxVvtsdmGmR5D47S8q5afbfDckfKQFpcr4wm

Is it missing config option for storage limits?  or something else related to gas?

**Comment by utdrmac** [comment]
Understand that "upgrade to new storage" and "storage_exhausted" have absolutely nothing to do with each other. The former is related to the physical storage on-disk of the blockchain database, and the later is storage on the blockchain.

The reason for . this error you received is because your batch payment . included an address with a balance of 0xtz (https://tzstats.com/tz1XcmFgCdo8j8UamjT8gVZpj6Ks44RGrSSc) . Because there is 0 balance, the blockchain "removed" it from the chain. Thus, to pay this address, it must be re-activated and a burn fee must be paid.

We experienced the same issue and I believe someone else also posted this same issue here.

**Comment by sriney-staked** [comment]
ok, thanks, I was able to use the rules_map to exclude the offending addresses.

**Comment by utdrmac** [comment]
Relates to #159
