### ISSUE TITLE
retry_failed.py error: missing 'node_addr'

### ISSUE THREAD

**Issue by Xa52c** [habanoz/tezos-reward-distributor#213]
if you run python3 src/retry_failed.py with any arguments it gives the error:

MainThread - master configuration file not present.
Traceback (most recent call last):
  File "src/retry_failed.py", line 200, in <module>
    main(args)
  File "src/retry_failed.py", line 82, in main
    config_client_manager = SimpleClientManager(client_path)
TypeError: __init__() missing 1 required positional argument: 'node_addr'

**Comment by utdrmac** [comment]
@Xa52c Can you test if this small change fixes your issue?
https://github.com/habanoz/tezos-reward-distributor/pull/214/files

**Comment by utdrmac** [comment]
The problem is that the failed csv file does not contain each addresses current balance, thus the value internally is set to 0. If the current_balance is 0, then TRD must decide to “reactivate” the account by paying the burn fee. Since all of the address in the retry csv file say 0 balance, then all are being treated as "needs reactivation" and the burn fee is being deducted from their  rewards, blindly.

Fetching the current balance of each address happens several steps/phases before retry_failed starts processing, which is normal in a normal payment execution.
