### ISSUE TITLE
Ability to ignore specific delegators

### ISSUE THREAD

**Issue by utdrmac** [habanoz/tezos-reward-distributor#46]
* Feature Request *
We have several KT1 addresses that delegate to us which are internal/testing addresses. We own/control these addresses. In some cases, we would prefer to not waste the txn fee by sending rewards to "ourselves".

Attempted to add these addresses to specials_map with fee of 100% but that produced a bunch of negative payout values.

* Possible Solution *
Adding an `ignore_delegators` array to BusinessConfiguration. Payouts are still calculated as normal but any address in this array is not added to the final batch operation.

**Comment by habanoz** [comment]
we have excluded_delegators_set already. However, it excludes delegators at reward calculation stage. The share of excluded delegators is shared among others. In this request share of the excluded needs to remain in the staking balance.

We are going to have a lot of different configuration parameters due to minor differences in needs. 

I would like to suggest a holistic configuration:

Let's have another map called payment_mapping_dict, a dictionary of PKH and target description pairs.

A PKH is either a tz or a kt address.
A target description is a text which may have some of the values below:
- another PKH: make payments to this address rather than original delegator KT address. Requires reporting change. Requested in #39 
- Ignore : The same behavior as excluded delegators set. Requested in #8 
- donotpay: the same behavior as this request expects.

Present and future target descriptions need to be mutually exclusive. e.g. we cannot 'ignore' and 'donotpay' the same delegator at the same time. 

What do you (all users) thing?

**Comment by SemElVik** [comment]
`payment_mapping_dict`  looks like a logical sentence.
if really need it.

**Comment by habanoz** [comment]
In V5 this is supported.
Use rules map to exclude anyone by setting a destination to it. Valid destinations are:

TOB = To Balance
TOF = To Founders
TOE = To everyone

Also rewards for accounts below min delegation amount can be paid to target by using mindelegation key. See examples/*.yaml file.
