### ISSUE TITLE
Why is script listing known contracts?

### ISSUE THREAD

**Issue by utdrmac** [habanoz/tezos-reward-distributor#57]
When I view debug output, the script is calling ` list known contracts` and `list known addresses`. Why is the script getting such information? Why does the script need to know about other addresses in my wallet? I'm not sending payments from any of these addresses, so why does the script need to know?

**Comment by habanoz** [comment]
Legitimate question. 

Before discussing "why?" we need to understand that not all people trying to bake and use the software for payments are tech savvy. Even from the experienced peoples' standpoint, the application by nature has many configuration parameters which can easily be mistyped. 

After dealing with many failure reports from users It was clear that the source of the problems for the majority of the cases was incorrect user input. This is why in V3 user input validation was put so much emphasis. 

Each user input is validated against appropriate validation criteria. Most of the validation is put to payment address input because it was the source of the majority of the failure cases.

A payment address can be an alias or a PKH. It can be an implicit account or an originated contract. A payment address requires the secret key to be known so that transactions can be signed. Note that TRD does not do signing, tezos client does. So TRD does not need to know SK, but needs to check that it is known by the client. If payment address is an originated account, its manager account needs to be in the system; because manager signs for the originated account. 

In order to make these checks, it is necessary to know:
- list of addresses, aliases and SK status. 
- list of contracts and their aliases
- manager of originated contracts

--
Another requirement is that public address of the payment account needs to be revealed. This check is based on tzscan data, because I do not know a way of getting it from client.

**Comment by habanoz** [comment]
There is a way to avoid TRD from querying account information. 

Relevant information can be provided in master.yaml. Here I share an example master.yaml for those who are interested. 

```
version : 2.0
managers: {
  "KT1EVBSE6cevRV8Uau2uySzjuYvWh7NDhnfy": "tz1YWn9eVvXuRkUxNwewVdYr71QKA8cr5Ane",
  "KT1eVBSE6cevRV8Uau2uySzjuYvWh7NDhnfy": "tz1yWn9eVvXuRkUxNwewVdYr71QKA8cr5Ane"
}
addresses_by_pkh: {
  "tz1YWn9eVvXuRkUxNwewVdYr71QKA8cr5Ane": {
    'alias': "mainnetme",
    "sk": true
  },
  "tz3WXYtyDUNL91qfiCJtVUX746QpNv5i5ve5": {
    'alias': "alphanet1",
    "sk": true
  },
  "tz1RW2P6sMLUMDVWimgYK6LDgsFfRALPEXik": {
    'alias': "alphanet2",
    "sk": true
  }
}

contracts_by_alias: {
  "pk1": "KT1EVBSE6cevRV8Uau2uySzjuYvWh7NDhnfy"
}
```

Note that this is for primarly testing porpuses. Input is not validated. If input is not correct TRD fails. Use of this method is neither suggested nor supported.

**Comment by utdrmac** [comment]
Thanks for the explanation. As a fellow developer, I completely understand user mistypes are the common source of issues.
